export const smartMoneyStyles = {
  page: "min-h-screen bg-slate-50 dark:bg-slate-950 px-4 py-8",
  container: "mx-auto max-w-5xl",

  header: {
    wrap: "mb-6 border-b border-slate-200 pb-4 dark:border-slate-700",
    title: "text-xl font-bold tracking-tight text-slate-800 dark:text-slate-100",
  },

  tabs: {
    wrap: "mb-4 flex gap-1 rounded-lg border border-slate-200 bg-white p-1 dark:border-slate-700 dark:bg-slate-900 w-fit",
    btn: "rounded-md px-4 py-2 text-sm font-medium transition-colors",
    active: "bg-blue-900 text-white dark:bg-blue-700",
    inactive: "text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800",
  },

  card: "overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900",

  table: {
    wrap: "w-full",
    header: "grid grid-cols-[3rem_1fr_7rem_10rem_9rem] border-b border-slate-200 bg-slate-100 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-400",
    row: "grid grid-cols-[3rem_1fr_7rem_10rem_9rem] items-center border-b border-slate-100 px-4 py-3.5 last:border-b-0 hover:bg-blue-50 dark:border-slate-800 dark:hover:bg-slate-800",
    colRank: "text-sm font-mono text-slate-400 dark:text-slate-500",
    colName: "text-sm font-medium text-slate-800 dark:text-slate-100",
    colCode: "text-sm font-mono text-slate-500 dark:text-slate-400",
    colAmount: "text-right text-sm tabular-nums text-slate-700 dark:text-slate-200",
    colQuantity: "text-right text-sm tabular-nums text-slate-500 dark:text-slate-400",
  },

  loading: "flex items-center justify-center gap-2 py-20 text-slate-400 dark:text-slate-500 text-sm",
  error: "flex items-center justify-center py-20 text-red-500 text-sm",
  empty: "flex flex-col items-center justify-center gap-2 py-20 text-slate-400 dark:text-slate-500",
  emptyText: "text-sm",

  chart: {
    panel: "mt-4 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900",
    header: "flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-700",
    stockName: "text-base font-semibold text-slate-800 dark:text-slate-100",
    stockCode: "ml-2 text-sm text-slate-400 dark:text-slate-500",
    closeBtn: "rounded p-1 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-800 dark:hover:text-slate-300",
    body: "px-2 py-4",
    loading: "flex items-center justify-center py-16 text-slate-400 dark:text-slate-500 text-sm",
    error: "flex items-center justify-center py-16 text-red-500 text-sm",
  },

  tableRowClickable: "grid grid-cols-[3rem_1fr_7rem_10rem_9rem] items-center border-b border-slate-100 px-4 py-3.5 last:border-b-0 cursor-pointer hover:bg-blue-50 dark:border-slate-800 dark:hover:bg-slate-800",
  tableRowSelected: "grid grid-cols-[3rem_1fr_7rem_10rem_9rem] items-center border-b border-slate-100 px-4 py-3.5 bg-blue-50 dark:border-slate-800 dark:bg-slate-800",

  concentrated: {
    section: "mb-8",
    sectionHeader: "mb-4 flex items-center justify-between",
    sectionTitle: "text-base font-semibold text-slate-800 dark:text-slate-100",
    dropdown: "rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-sm text-slate-700 shadow-sm transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200",
    grid: "grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4",
    card: "flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900",
    cardHeader: "flex items-start justify-between gap-2",
    cardName: "text-sm font-semibold text-slate-800 dark:text-slate-100 leading-tight",
    cardCode: "shrink-0 rounded bg-slate-100 px-1.5 py-0.5 text-xs font-mono text-slate-500 dark:bg-slate-800 dark:text-slate-400",
    cardAmounts: "flex flex-col gap-1",
    cardAmountRow: "flex items-center justify-between text-xs",
    cardAmountLabel: "text-slate-500 dark:text-slate-400",
    cardAmountValue: "tabular-nums font-medium text-slate-700 dark:text-slate-200",
    scoreWrap: "flex flex-col gap-1",
    scoreLabel: "flex items-center justify-between text-xs",
    scoreLabelText: "text-slate-500 dark:text-slate-400",
    scoreLabelValue: "font-semibold text-blue-700 dark:text-blue-400",
    scoreBar: "h-2 w-full overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800",
    scoreBarFill: "h-full rounded-full bg-gradient-to-r from-blue-500 to-blue-700 transition-all duration-500",
    loading: "flex items-center justify-center py-12 text-slate-400 dark:text-slate-500 text-sm",
    error: "flex items-center justify-center py-12 text-red-500 text-sm",
    empty: "flex items-center justify-center py-12 text-slate-400 dark:text-slate-500 text-sm",
  },

  portfolio: {
    toolbar: "mb-4 flex flex-wrap items-center gap-3",
    selector: "rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-sm text-slate-700 shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200",
    toggleWrap: "ml-auto flex items-center gap-2",
    toggleLabel: "text-sm text-slate-600 dark:text-slate-300",
    toggle: "relative inline-flex h-5 w-9 cursor-pointer rounded-full transition-colors focus:outline-none",
    toggleOn: "bg-blue-600",
    toggleOff: "bg-slate-300 dark:bg-slate-600",
    toggleThumb: "pointer-events-none absolute top-0.5 h-4 w-4 rounded-full bg-white shadow transition-transform",
    toggleThumbOn: "translate-x-4",
    toggleThumbOff: "translate-x-0.5",
    table: {
      wrap: "w-full",
      header: "grid grid-cols-[1fr_6rem_8rem_9rem_6rem_8rem] border-b border-slate-200 bg-slate-100 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-400",
      row: "grid grid-cols-[1fr_6rem_8rem_9rem_6rem_8rem] items-center border-b border-slate-100 px-4 py-3.5 last:border-b-0 dark:border-slate-800",
      colName: "text-sm font-medium text-slate-800 dark:text-slate-100",
      colTicker: "text-sm font-mono text-slate-500 dark:text-slate-400",
      colNumber: "text-right text-sm tabular-nums text-slate-600 dark:text-slate-300",
      colWeight: "text-right text-sm tabular-nums font-medium text-slate-700 dark:text-slate-200",
      colBadge: "flex justify-end",
    },
    badge: {
      base: "inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold",
      NEW: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-400",
      INCREASED: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-400",
      DECREASED: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-400",
      CLOSED: "bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-400",
    },
    reportedAt: "text-xs text-slate-400 dark:text-slate-500",
    idle: "flex items-center justify-center py-20 text-slate-400 dark:text-slate-500 text-sm",
    loading: "flex items-center justify-center py-20 text-slate-400 dark:text-slate-500 text-sm",
    error: "flex items-center justify-center py-20 text-red-500 text-sm",
    empty: "flex items-center justify-center py-20 text-slate-400 dark:text-slate-500 text-sm",
  },
};
